import assert from "node:assert/strict";
import { handleAppSchedulesPage } from "./app-schedules-page.js";

const env = { THREADS_KV: { async get(key) { return key === "admin_session:session-1" ? "valid" : null; } } };
const response = await handleAppSchedulesPage(new Request("https://x/app/schedules", { headers: { cookie: "admin_session=session-1" } }), env);
const page = await response.text();
assert.equal(response.status, 200);
assert.match(page, /id="schedule-form"/u);
assert.equal(page.includes("/api/schedules"), true);
assert.match(page, /Asia\/Seoul/u);
assert.match(page, /기존 Cloudflare 자동 실행/u);
assert.match(page, /런타임 스케줄러는 전환 준비 중/u);
assert.match(page, /actualProductionNextRunAt/u);
assert.doesNotMatch(page, /10 23 \* \* \*|30 2 \* \* \*/u);
assert.match(page, /현재 자동 실행 방식/u);
assert.match(page, /현재 운영 상태/u);
assert.match(page, /실제 자동 실행/u);
assert.match(page, /실패 사유/u);
assert.match(page, /콘텐츠 포맷 검증/u);
assert.match(page, /처리 중/u);
assert.match(page, /기존 Cloudflare 자동 실행/u);
assert.match(page, /전환 준비 중/u);
assert.match(page, /런타임 스케줄러 상태/u);
assert.match(page, /전환 준비용 상태/u);
assert.match(page, /실제 알람/u);
assert.match(page, /알람 예정 시각/u);
assert.match(page, /계산된 다음 시각/u);
assert.match(page, /활성 일정 수/u);
assert.match(page, /최근 런타임 상태/u);
assert.match(page, /주의/u);
assert.match(page, /등록되지 않음/u);
assert.match(page, /실행 억제됨/u);
assert.match(page, /id="schedule-reconcile"/u);
assert.match(page, /\/api\/schedules\/reconcile/u);
assert.match(page, /window\.confirm/u);
assert.match(page, /현재 실제 자동 게시 방식은 변경되지 않습니다/u);
assert.match(page, /알람 상태를 확인하고 필요한 경우 복구했습니다/u);
assert.doesNotMatch(page, /현재 실제 자동 실행 일정/u);
assert.doesNotMatch(page, /production-schedule-overview/u);
assert.doesNotMatch(page, /최근 자동 실행/u);
assert.doesNotMatch(page, /recentGeneralAutoExecutions|\/admin\/auto-post\/status|diagnostic\?\.attempts/u);
assert.doesNotMatch(page, /['"]자동 실행 중['"]/u);
assert.doesNotMatch(page, /Durable Object|Wrangler|cron/iu);
assert.equal((await handleAppSchedulesPage(new Request("https://x/app/schedules"), env)).status, 302);
console.log("app schedules page fixture passed");
