import assert from "node:assert/strict";
import { handleAppSchedulesPage } from "./app-schedules-page.js";

const env = { THREADS_KV: { async get(key) { return key === "admin_session:session-1" ? "valid" : null; } } };
const response = await handleAppSchedulesPage(new Request("https://x/app/schedules", { headers: { cookie: "admin_session=session-1" } }), env);
const page = await response.text();
assert.equal(response.status, 200);
assert.match(page, /id="schedule-form"/u);
assert.equal(page.includes("/api/schedules"), true);
assert.match(page, /Asia\/Seoul/u);
assert.match(page, /현재 자동 실행 방식/u);
assert.match(page, /최근 자동 실행/u);
assert.match(page, /현재 운영 상태/u);
assert.match(page, /다음 실제 실행/u);
assert.match(page, /기존 자동 실행 일정으로 운영 중/u);
assert.match(page, /전환 준비 상태/u);
assert.match(page, /전환 준비 중/u);
assert.match(page, /최근 자동 실행 기록이 없습니다/u);
assert.doesNotMatch(page, /['"]자동 실행 중['"]/u);
assert.doesNotMatch(page, /Durable Object|Wrangler|cron/iu);
assert.equal((await handleAppSchedulesPage(new Request("https://x/app/schedules"), env)).status, 302);
console.log("app schedules page fixture passed");
